"""
Apex AI Marketing - File Service

Manages deliverable files: saving content to disk, exporting
to various formats, and retrieving file paths.
"""

import logging
import uuid
from datetime import datetime
from pathlib import Path

import markdown

from config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()

DELIVERABLES_ROOT = Path(__file__).resolve().parent.parent / settings.DELIVERABLES_DIR


class FileService:
    """File management for deliverables and exports."""

    def __init__(self) -> None:
        DELIVERABLES_ROOT.mkdir(parents=True, exist_ok=True)

    # ── Save deliverable to disk ──────────────────────────────────────
    async def save_deliverable(
        self,
        content: str,
        filename: str | None = None,
        fmt: str = "md",
        subfolder: str | None = None,
    ) -> Path:
        """Persist deliverable content to the filesystem.

        Parameters
        ----------
        content : str
            The raw text content (Markdown, HTML, or plain text).
        filename : str, optional
            Desired filename (without extension). Auto-generated if omitted.
        fmt : str
            File format / extension: ``"md"``, ``"html"``, ``"txt"``, ``"json"``.
        subfolder : str, optional
            Optional subfolder inside the deliverables directory
            (e.g. a client name or engagement id).

        Returns
        -------
        pathlib.Path
            Absolute path to the saved file.
        """
        if filename is None:
            timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
            filename = f"deliverable_{timestamp}_{uuid.uuid4().hex[:8]}"

        target_dir = DELIVERABLES_ROOT
        if subfolder:
            target_dir = target_dir / subfolder
            target_dir.mkdir(parents=True, exist_ok=True)

        file_path = target_dir / f"{filename}.{fmt}"
        file_path.write_text(content, encoding="utf-8")

        logger.info("Saved deliverable: %s", file_path)
        return file_path

    # ── Export Markdown to HTML ───────────────────────────────────────
    async def export_to_html(
        self,
        md_content: str,
        filename: str | None = None,
        subfolder: str | None = None,
        title: str = "Deliverable",
    ) -> Path:
        """Convert Markdown content to a standalone HTML file.

        Parameters
        ----------
        md_content : str
            Markdown source text.
        filename : str, optional
            Desired filename (without extension).
        subfolder : str, optional
            Optional subfolder.
        title : str
            HTML ``<title>`` tag value.

        Returns
        -------
        pathlib.Path
            Absolute path to the saved HTML file.
        """
        html_body = markdown.markdown(
            md_content,
            extensions=["tables", "fenced_code", "toc", "meta"],
        )

        html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - {settings.BRAND_NAME}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 900px;
            margin: 2rem auto;
            padding: 0 1.5rem;
            line-height: 1.6;
            color: #1a1a2e;
        }}
        h1, h2, h3 {{ color: #0f0f23; }}
        table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
        th, td {{ border: 1px solid #ddd; padding: 0.5rem 0.75rem; text-align: left; }}
        th {{ background: #f4f4f8; }}
        code {{ background: #f4f4f8; padding: 0.15rem 0.4rem; border-radius: 3px; font-size: 0.9em; }}
        pre code {{ display: block; padding: 1rem; overflow-x: auto; }}
        .footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #eee; font-size: 0.85rem; color: #666; }}
    </style>
</head>
<body>
{html_body}
<div class="footer">
    <p>Generated by {settings.BRAND_NAME} | {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}</p>
</div>
</body>
</html>"""

        return await self.save_deliverable(
            content=html_doc,
            filename=filename,
            fmt="html",
            subfolder=subfolder,
        )

    # ── Export Markdown to PDF (via HTML intermediary) ─────────────────
    async def export_to_pdf(
        self,
        md_content: str,
        filename: str | None = None,
        subfolder: str | None = None,
        title: str = "Deliverable",
    ) -> Path:
        """Convert Markdown to PDF.

        Attempts to use WeasyPrint for PDF generation. If WeasyPrint is
        not installed, falls back to saving as Markdown.
        """
        try:
            from weasyprint import HTML as WeasyprintHTML

            # First convert to HTML
            html_path = await self.export_to_html(
                md_content=md_content,
                filename=f"{filename or 'temp'}_html",
                subfolder=subfolder,
                title=title,
            )

            # Determine PDF output path
            if filename is None:
                timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
                filename = f"deliverable_{timestamp}_{uuid.uuid4().hex[:8]}"

            target_dir = DELIVERABLES_ROOT
            if subfolder:
                target_dir = target_dir / subfolder
                target_dir.mkdir(parents=True, exist_ok=True)

            pdf_path = target_dir / f"{filename}.pdf"

            WeasyprintHTML(filename=str(html_path)).write_pdf(str(pdf_path))
            logger.info("Exported PDF: %s", pdf_path)

            # Clean up the intermediate HTML
            html_path.unlink(missing_ok=True)

            return pdf_path

        except ImportError:
            logger.warning(
                "WeasyPrint not installed - falling back to Markdown export"
            )
            return await self.save_deliverable(
                content=md_content,
                filename=filename,
                fmt="md",
                subfolder=subfolder,
            )

    # ── Get path to a deliverable ─────────────────────────────────────
    def get_deliverable_path(
        self,
        filename: str,
        subfolder: str | None = None,
    ) -> Path | None:
        """Return the absolute path to a deliverable if it exists."""
        target_dir = DELIVERABLES_ROOT
        if subfolder:
            target_dir = target_dir / subfolder

        file_path = target_dir / filename
        if file_path.exists():
            return file_path
        return None
