"""
Apex AI Marketing - Weekly Report Template

8-section weekly performance report delivered to clients every Monday.

Sections:
  1. Executive Summary
  2. KPI Dashboard
  3. Engine Performance Breakdown
  4. Content Delivered This Week
  5. Experiment Updates
  6. Competitive Intelligence
  7. Insights & Learnings
  8. Next Week's Plan
"""

WEEKLY_REPORT_TEMPLATE = """# Weekly Growth Report

**Client:** {{ client_name }}{% if company %} ({{ company }}){% endif %}
**Period:** {{ week_start }} to {{ week_end }}
**Report Date:** {{ report_date }}

---

## 1. Executive Summary

{{ executive_summary | default("This week's performance summary for " + (company or client_name) + ".") }}

**Overall Status:** {{ overall_status | default("On Track") }}

### Week at a Glance
| Metric | This Week | Last Week | Change |
|--------|-----------|-----------|--------|
{% for metric in summary_metrics | default([]) %}| {{ metric.name }} | {{ metric.current }} | {{ metric.previous }} | {{ metric.change }} |
{% endfor %}

---

## 2. KPI Dashboard

### Primary KPIs vs. Targets

| KPI | Target | Actual | % of Target | Trend |
|-----|--------|--------|-------------|-------|
{% for kpi in kpis | default([]) %}| {{ kpi.name }} | {{ kpi.target }} | {{ kpi.actual }} | {{ kpi.pct_of_target }} | {{ kpi.trend }} |
{% endfor %}

### Traffic Overview
{{ traffic_overview | default("Traffic metrics pending analytics integration.") }}

### Conversion Metrics
{{ conversion_metrics | default("Conversion tracking pending integration.") }}

---

## 3. Engine Performance Breakdown

{% for engine in engines | default([]) %}
### {{ engine.engine_name }}

**Status:** {{ engine.status | default("Active") }}

{{ engine.summary | default("Engine performance details pending.") }}

| Deliverable | Status | Performance |
|-------------|--------|-------------|
{% for d in engine.deliverables | default([]) %}| {{ d.title }} | {{ d.status }} | {{ d.performance | default("--") }} |
{% endfor %}

{% if engine.kpi_targets %}
**KPI Progress:**
{% for kpi_name, kpi_target in engine.kpi_targets.items() %}
- {{ kpi_name }}: Target {{ kpi_target }} | Actual: {{ engine.kpi_actuals.get(kpi_name, "--") if engine.kpi_actuals is defined else "--" }}
{% endfor %}
{% endif %}

{% endfor %}

---

## 4. Content Delivered This Week

{% if deliverables_this_week %}
| # | Deliverable | Type | Status | Notes |
|---|-------------|------|--------|-------|
{% for d in deliverables_this_week %}| {{ loop.index }} | {{ d.title }} | {{ d.type }} | {{ d.status }} | {{ d.notes | default("") }} |
{% endfor %}
{% else %}
No deliverables completed this week.
{% endif %}

**Deliverables in pipeline:**
{% for d in pipeline_deliverables | default([]) %}
- {{ d.title }} ({{ d.type }}) -- Expected: {{ d.expected_date | default("TBD") }}
{% endfor %}

---

## 5. Experiment Updates

### Running Experiments
{% for exp in running_experiments | default([]) %}
- **{{ exp.hypothesis | truncate(100) }}**
  - Variable: {{ exp.variable }}
  - Metric: {{ exp.metric }}
  - Status: {{ exp.status }} | Days remaining: {{ exp.days_remaining }}
{% endfor %}

### Completed This Week
{% for exp in completed_experiments | default([]) %}
- **{{ exp.hypothesis | truncate(100) }}**
  - Result: {{ exp.result }}
  - Decision: {{ exp.decision }}
  - Learning: {{ exp.learning }}
{% endfor %}

{% if not running_experiments and not completed_experiments %}
No active experiments this week.
{% endif %}

---

## 6. Competitive Intelligence

{{ competitive_intel | default("Competitive monitoring summary pending.") }}

### Notable Competitor Moves
{% for move in competitor_moves | default([]) %}
- **{{ move.competitor }}**: {{ move.action }}
{% endfor %}

---

## 7. Insights & Learnings

### Key Insights This Week
{% for insight in insights | default([]) %}
{{ loop.index }}. **{{ insight.title }}**: {{ insight.detail }}
{% endfor %}

### Data-Driven Observations
{{ observations | default("Observations will be populated as data accumulates.") }}

---

## 8. Next Week's Plan

### Priority Actions
{% for action in next_week_actions | default([]) %}
{{ loop.index }}. {{ action }}
{% endfor %}

### Scheduled Deliverables
{% for d in next_week_deliverables | default([]) %}
- {{ d.title }} ({{ d.type }}) -- {{ d.day | default("TBD") }}
{% endfor %}

### Experiments to Launch
{% for exp in experiments_to_launch | default([]) %}
- {{ exp.hypothesis | truncate(100) }}
{% endfor %}

---

*Report generated by Apex AI Marketing's Reporting Engine.*
*Questions? Contact your account manager or reply to this email.*
"""


def render_weekly_report(
    client_name: str,
    company: str = "",
    week_start: str = "",
    week_end: str = "",
    engagements: list = None,
    metrics: dict = None,
    language: str = "en",
    **kwargs,
) -> str:
    """Render the weekly report template.

    Args:
        client_name: Client contact name.
        company: Company name.
        week_start: Start date of the reporting week.
        week_end: End date of the reporting week.
        engagements: List of engine engagement dicts.
        metrics: Metrics data gathered for the period.
        language: Language code.
        **kwargs: Additional template variables.

    Returns:
        Rendered markdown string.
    """
    from jinja2 import Template
    from datetime import date

    engagements = engagements or []
    metrics = metrics or {}

    context = {
        "client_name": client_name,
        "company": company,
        "week_start": week_start,
        "week_end": week_end,
        "report_date": date.today().isoformat(),
        # Engine data
        "engines": engagements,
        # Metrics
        "summary_metrics": metrics.get("summary_metrics", []),
        "kpis": metrics.get("kpis", []),
        "traffic_overview": metrics.get("traffic_overview"),
        "conversion_metrics": metrics.get("conversion_metrics"),
        "overall_status": metrics.get("overall_status", "On Track"),
        "executive_summary": metrics.get("executive_summary"),
        # Deliverables
        "deliverables_this_week": metrics.get("deliverables_this_week", []),
        "pipeline_deliverables": metrics.get("pipeline_deliverables", []),
        # Experiments
        "running_experiments": metrics.get("running_experiments", []),
        "completed_experiments": metrics.get("completed_experiments", []),
        # Competitive
        "competitive_intel": metrics.get("competitive_intel"),
        "competitor_moves": metrics.get("competitor_moves", []),
        # Insights
        "insights": metrics.get("insights", []),
        "observations": metrics.get("observations"),
        # Next week
        "next_week_actions": metrics.get("next_week_actions", []),
        "next_week_deliverables": metrics.get("next_week_deliverables", []),
        "experiments_to_launch": metrics.get("experiments_to_launch", []),
        **kwargs,
    }

    template = Template(WEEKLY_REPORT_TEMPLATE)
    return template.render(**context)
